apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-9ngsb
  generation: 128
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-bl-consul
  name: bl-consul
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bl-consul
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8500,"dnsName":"bl-consul-nodeport","kind":"NodePort","name":"8500tcp326001","protocol":"TCP","sourcePort":32600}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bl-consul
    spec:
      containers:
      - args:
        - agent
        - -server
        - -bootstrap-expect
        - "1"
        - -ui
        - -client
        - 0.0.0.0
        - -data-dir=/consul/data
        - -disable-host-node-id=true
        image: consul:1.1.0
        imagePullPolicy: Always
        name: bl-consul
        ports:
        - containerPort: 8500
          name: 8500tcp326001
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /consul/data
          name: consul-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/backendless/shared/consul/data
          type: DirectoryOrCreate
        name: consul-data
